apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-sp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:GCLIM/test-app-sp.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: test-app-sp-namespace

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true