---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: test-app-sp-namespace
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test-app-sp-namespace
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: test-app-sp-namespace
    name: test-app-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access