apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-secrets-provider-k8s
  name: test-app-secrets-provider-k8s
  namespace: test-app-sp-namespace
spec:
  selector:
    matchLabels:
      app: test-app-secrets-provider-k8s
  replicas: 1
  template:
    metadata:
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-enabled: "true"
        conjur.org/secrets-refresh-interval: 10s
      labels:
        app: test-app-secrets-provider-k8s
    spec:
      serviceAccountName: test-app-sa
      containers:
      - name: test-app
        image: registry.gcloud101.com/authnk8s/test-app:005
        command: [ "sleep" ]
        args: [ "infinity" ]
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: VAR_ID
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
      - image: registry.gcloud101.com/cyberark/secrets-provider-for-k8s:latest
        imagePullPolicy: Always
        name: cyberark-secrets-provider-for-k8s
        env:
          - name: CONJUR_AUTHN_LOGIN
            value: apps/authn-k8s/test-app-sp
          - name: CONTAINER_MODE
            value: sidecar
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_SECRETS
            value: db-credentials
          - name: SECRETS_DESTINATION
            value: k8s_secrets
        envFrom:
          - configMapRef:
              name: conjur-connect
        # volumeMounts:
        # - mountPath: /run/conjur
        #   name: access-token
        # - mountPath: /etc/conjur/ssl
        #   name: conjur-certs
        # - mountPath: /conjur/podinfo
        #   name: podinfo
      imagePullSecrets:
        - name: gcloud101cred
      # volumes:
      # - emptyDir:
      #     medium: Memory
      #   name: access-token
      # - emptyDir:
      #     medium: Memory
      #   name: conjur-certs
      # - downwardAPI:
      #     defaultMode: 420
      #     items:
      #     - fieldRef:
      #         apiVersion: v1
      #         fieldPath: metadata.annotations
      #       path: annotations
      #   name: podinfo